### ISSUE TITLE
OptimisticLockBehavior doesnt work. 

### ISSUE THREAD

**Issue by tarranjones** [yiisoft/yii2#16456]
https://github.com/yiisoft/yii2/blob/master/framework/behaviors/OptimisticLockBehavior.php#L128

As it stand OptimisticLockBehavior expected the submission of the lock attribute like so 
```php
echo Html::hiddenInput('lock', $value); // <input name="lock" type="hidden" />
```
shouldn't it expect the following by default

```php
echo   $form->field($model, 'lock')->hiddenInput(); // <input name="ModelName[lock]" type="hidden" />
```

This is how i think the  `getValue($event)` should behave.
```php
    /**
     * {@inheritdoc}
     *
     * In case of `null`, value will be parsed from [[\yii\web\Request::getBodyParam()|getBodyParam()]] or set to 0.
     */
    protected function getValue($event)
    {
        if ($this->value === null) {
            $lock = $this->getLockAttribute();
            $scope = $this->owner->formName();
            $params = Yii::$app->getRequest()->getBodyParam($scope);
            $input = isset($params[$lock]) ? $params[$lock] : null;

            $isValid = $input && (new NumberValidator())->validate($input);
            return $isValid ? $input : 0;
        }
        return parent::getValue($event);
    }
```

**Comment by samdark** [comment]
@tunecino would you please check it? Thanks.

**Comment by tunecino** [comment]
Yes that make sense. But I don't think suggested code will pass tests as it solves the WEB form case but not REST inputs or a model class overriding `formName()`. Maybe something like this instead:

```php
protected function getValue($event)
{
    if ($this->value === null) {
        $request = Yii::$app->getRequest();
        $lock = $this->getLockAttribute();
        $formName = $this->owner->formName();
        $formValue = $formName ? ArrayHelper::getValue($request->getBodyParams(), $formName.'.'.$lock) : null;
        $input = $request->getBodyParam($lock, $formValue);
        $isValid = $input && (new NumberValidator())->validate($input);
        return $isValid ? $input : 0;
    }

    return parent::getValue($event);
}
```
@tarranjones do you want to send a PR or should I do it?

**Comment by tarranjones** [comment]
Also the getValue method doesn't take into consideration the `$owner->{$lock}` value, so the following code would throw a `StaleObjectException`

```php   
$user = User::findByUsername($username);
$user->last_logged_in = time();
$user->save();
```
This could be a possible fix. 
```php
$input = $request->getBodyParam($lock, $formValue);
if($input === null && $this->owner->$lock){
   $input = $this->owner->$lock;
}
$isValid = $input && (new NumberValidator())->validate($input);
return $isValid ? $input : 0;

**Comment by tarranjones** [comment]
@tunecino , yep that will definitely break it. 

I think i'll do something like this when/if the issue occurs. 

```php
public function behaviors()
{
    return [
        OptimisticLockBehavior::className(),
        'value' => function ($event) {
            if($this->owner->scenario === 'login'){
                return $this->owner->$lock; 
            }
            $this->value = null;
            return $this->getValue($event)
        },
    ];
}
```

Thanks

**Comment by samdark** [comment]
So the issue is solved, right?

**Comment by tunecino** [comment]
@samdark Yes the PR fixes the mentioned issue. But let me add few lines in doc to mention that adding this behavior make the model class useless for internal use and should be better added to a child class tied to controllers related to user inputs. Still not sure if that makes it complicated enough but I see no better alternatives.

**Comment by samdark** [comment]
OK. Ping me when you'll add docs.
