### ISSUE TITLE
Yii2-authclient (Twitter, Could not authenticate you, code 32)

### ISSUE THREAD

**Issue by zelenin** [yiisoft/yii2#7224]
I try send tweet to Twitter using yii2-authclient. I get token, do api request not requiring hmac-signature check - it's ok:

```php
$twitter = new Twitter([
    'accessToken' => $token,
    'consumerKey' => $client->consumerKey,
    'consumerSecret' => $client->consumerSecret
]);

$response = $twitter->api('statuses/home_timeline.json', 'GET', [
    'count' => 50,
    'trim_user' => 0
]);
```

If I request api method requiring hmac-signature

```php
$response = $twitter->api('statuses/update.json', 'POST', [
    'status' => $message
]);
```
I get error: ```Request failed with code: 401, message: {"errors":[{"message":"Could not authenticate you","code":32}]}```
Google says that hmac-signature calculated wrong - just guess.
I try this method with other library but with the same token and it's ok:

```php
$twitter = new TwitterOAuth($client->consumerKey, $client->consumerSecret, $token->token, $token->tokenSecret);
$response = $twitter->post('statuses/update', [
    'status' => $message
]);
```

**Comment by klimov-paul** [comment]
If you have it worked with other library, it whould be nice if you provide raw requests composed by `yii\authclient` and this library, so we can see where is the difference.

**Comment by ifrin** [comment]
I have the same problem with Twitter client!

**Comment by klimov-paul** [comment]
Resolved by commit b0df9ac

**Comment by woshibt** [comment]
Hi, I am seeing the same error even with the fix.

**Comment by joyeffect** [comment]
I receive same error when search tweets
```php
$token = new OAuthToken([
    'token' => 'token',
    'tokenSecret' => 'tokenSecret'
]);

$twitter = new Twitter([
    'accessToken' => $token,
    'consumerKey' => 'consumerKey',
    'consumerSecret' => 'consumerKeySecret'
]);
 
$twitter->api('search/tweets.json?q=@github&result_type=popular', 'GET');
```
Error: ```Request failed with code: 401, message: {"errors":[{"code":32,"message":"Could not authenticate you."}]}```

Other library ok:
```php
$twitter = new TwitterOAuth(
   $client->consumerKey, 
   $client->consumerSecret, 
   $client->getAccessToken()->token,
   $client->getAccessToken()->tokenSecret);

 $tweets = $twitter->get('search/tweets.json?q=@github&result_type=popular');
```

**Comment by thehiddennepali** [comment]
I am also having the same issue with the twitter auth I had checked the Resolved by commit b0df9ac

and I see there update but still getting 

Request failed with code: 401, message: {"errors":[{"code":32,"message":"Could not authenticate you."}]}

note sure what is wrong going with

**Comment by gbggit** [comment]
Using the array format seems to works:
```
$twitter->api('search/tweets.json', 'GET', ['q' => 'twitterapi']);
```

**Comment by demoniz** [comment]
Help my. Get error:

Request failed with code: 401, message: {"errors":[{"code":32,"message":"Could not authenticate you."}]}

what could be the reason?

**Comment by thehiddennepali** [comment]
It means it could not authenticate your tokens and secret, let me know what you were trying to achive

**Comment by glebmachine** [comment]
+1

**Comment by Luciuz** [comment]
same error :(

@thehiddennepali 
`{"errors":[{"code":89,"message":"Invalid or expired token."}]} ` appers if token is invalid

**Comment by dodobook** [comment]
+1

**Comment by Buliwyfa** [comment]
+1
