### ISSUE TITLE
DateValidator with ICU year format not strict

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2#7514]
as @massimilianomancini mentioned [in this comment](https://github.com/yiisoft/yii2/issues/6553#issuecomment-71180691) there are some cases when the validation with ICU format is not correct.

For example:

````php
$validator = new DateValidator;
$validator->format = 'yyyy-MM-dd';
var_dump($validator->validate('14-12-11')); // boolean true

$validator = new DateValidator;
$validator->format = 'yy-MM-dd';
var_dump($validator->validate('2014-12-11')); // boolean true

$validator = new DateValidator;
$validator->format = 'yy-MM-dd';
var_dump($validator->validate('214-12-11')); // boolean true, timestamp: -55384304008, year: 0214

$validator = new DateValidator;
$validator->format = 'yMM-dd';
var_dump($validator->validate('2014-12-11')); // boolean true ?!

$validator = new DateValidator;
$validator->format = 'php:Y-m-d';
var_dump($validator->validate('14-12-11')); // boolean true, short year accepted?

$validator = new DateValidator;
$validator->format = 'php:y-m-d';
var_dump($validator->validate('2014-12-11')); // boolean false, correct
````
 What I'm trying to say, is that a strict validation of mysql date format is nearly impossible at the moment. Probably in most of those cases `$timestampAttribute` would have a wrong year value, for example 14 as year could be interpreted as 2014 instead of 1914.

**Comment by lynicidn** [comment]
:+1: good tests

**Comment by nkovacs** [comment]
This is not a bug, [14 is a valid year](https://en.wikipedia.org/wiki/14)
What you actually want to do is check that the year is within a certain range.

You could use timestampAttribute to save the timestamp, then add a custom validator on the timestamp that adds an error message to the original date attribute if the timestamp is outside some valid range (e.g. 1900 and 2100).

A min/max property (timestamps) could be added to DateValidator to make this easier.

**Comment by nkovacs** [comment]
From http://www.icu-project.org/apiref/icu4j/com/ibm/icu/text/SimpleDateFormat.html:

> If the year pattern does not have exactly two 'y' characters, the year is interpreted literally, regardless of the number of digits. So using the pattern "MM/dd/yyyy", "01/11/12" parses to Jan 11, 12 A.D.

Unfortunately, on a Debian server with php 5.5.14, `14-12-11` with format `yyyy-MM-dd` is parsed as `2014-12-11` (and there's no error). On my own computer with Ubuntu and php 5.5.12, it's correctly parsed as 14-12-11

**Comment by razvanphp** [comment]
I can understand that 14 is a valid year, even tho is not really what modern applications usually use. My problem is really with my first example, since I want to avoid any confusion and force all the time a 4 digit year, that's why I have 4 'y'. As the test shows, even 2 digits or 3 digits pass validation. This behavior is not the same with the `php:` 'Y' format.

In my opinion, the inclusion of ICU format in this validator is just misleading, as you can perfectly validate any date with PHP parse function, using notation familiar for every developer.

**Comment by nkovacs** [comment]
I agree, but unfortunately that is not how ICU works. Like I said, you'll have to check whether the timestamp is within a range. If you use the `php:` prefix, DateValidator will convert the php format to ICU, so you can't avoid the ICU behavior.

I found the change in ICU that causes 2 digit years to be parsed as-is if the pattern is yyyy: http://bugs.icu-project.org/trac/ticket/9836
So you'll need > 51.1, otherwise you can't detect these invalid values with the range check.

**Comment by nkovacs** [comment]
Or use a RegularExpressionValidator, if you don't need the flexibility of DateValidator.

**Comment by cebe** [comment]
> In my opinion, the inclusion of ICU format in this validator is just misleading, as you can perfectly validate any date with PHP parse function, using notation familiar for every developer.

Inclusion of ICU allows parsing dates like `12. Mai 2015` or `12 мая 2014`. this is not possible with PHP parser.

> If you use the php: prefix, DateValidator will convert the php format to ICU, so you can't avoid the ICU behavior.

This is not true, by using a `php:` prefix you are forcing it to use the PHP parser.

To validate a simple date format like `yyyy-mm-dd` you may combine the date validator with a regex validator to ensure strict behavior as suggested by @nkovacs.

I am going to add something about this behavior to the documentation.

**Comment by nkovacs** [comment]
> This is not true, by using a php: prefix you are forcing it to use the PHP parser.

You're right, I was confusing it with formatting.

Regexp is not really a solution if you have a multi-language app or complex date formats.
I've started working on a patch that adds a max/min check. If you have a newer version of ICU it should fix the two-digit year problem.

As for 'yMM-dd', I don't think that's a problem, since if you're not using the timestamp parsed by DateValidator, that means you expect the input to be in a specific format, and should probably use a regexp validator anyway.

**Comment by cebe** [comment]
> Regexp is not really a solution if you have a multi-language app or complex date formats.

this was only about the validation of mysql dates, for i18n input the current solution is just fine.

**Comment by tuuling** [comment]
Not exactly the same issue bit similar enough I guess.

I'm trying to validate user inputed dates. The built in date validator was the first choice, but I found out that it is not strict enough. The format might be correct, but it's still not what I'm looking for.

```php
$validator = new DateValidator;
$validator->format = 'm.d.Y';
var_dump($validator->validate('30.02.2014')); // boolean true
```

Currently I am using a custom validator for this:

```
['myDate', function ($attribute) {
                $date = $this->$attribute;
                $d = \DateTime::createFromFormat("d.m.Y", $date);
                if(!$d || $d->format("d.m.Y") != $date) {
                    $this->addError($attribute, 'date is incorrect'));
                }
}]
```

I propose a 'strict' parameter to the DateValidator

```
['myDate', 'date',
                'strict' => true,
                'format' => 'd.m.Y',
                'message' =>  'date is incorrect',
]
```

**Comment by nkovacs** [comment]
Validator's format is supposed to be in ICU format. 'm' is minute, 'd' is day of month, 'Y' is year of "Week of Year". Try 'php:m.d.Y' and it'll use php's format and php's parser.
