### ISSUE TITLE
Checkbox label not honoured when enclosedByLabel is true

### ISSUE THREAD

**Issue by svroemisse** [yiisoft/yii2#7895]
I've got a checkbox that I want to overwrite the label for. This works just fine with enclosedByLabel set to true but when I set it to false, I get the normal label.

This is using the yii2-bootstrap ActiveField class. 

Reiterating with code:
<?= $form->field($model, 'my_field')->checkbox(['label' => 'bla'], false) ?>
<?= $form->field($model, 'my_field')->checkbox(['label' => 'bla'], true) ?>

The first renders the label as 'bla' while the second doesn't.

**Comment by nigelterry** [comment]
I have the same problem. I have a solution that works for me, but I'm not confident of what other effects it might have. Here are the changes both in yii\bootstrap\ActiveField:

Line 210:
        return parent::checkbox($options);
to
        return parent::checkbox($options, $enclosedByLabel);

Line 374:
            } else {
to
            } elseif (!isset($this->parts['{label}'])) {

**Comment by mikehaertl** [comment]
Can you show a use case, where you need a checkbox without enclosing label in a BS3 form? I think, the BS3 documentation always uses enclosed labels: http://getbootstrap.com/css/#forms-example

**Comment by svroemisse** [comment]
nigelterry is right, I got it backward in the description, got it right in the code example.

As for the use case: I don't know, as that is not what I was trying to do. I just wanted to replace the default label in this one instance, with the default setting of *enclosedByLabel=true*. I only tried *false* to see what would happen. Turns out that works as advertised whereas in the default situation, it doesn't.

**Comment by mikehaertl** [comment]
@svroemisse I see now. Maybe you could fix the issue title then. I'll have a look.

**Comment by mikehaertl** [comment]
Here's a workaround for now:

```
<?= $form->field($model, 'my_field')->label('bla')->checkbox() ?>
```

This is actually even better if you want a simple textlabel. I will still try to fix the `label` in the options array, but you should be aware that if you pass the label there, it will *not* be surrounded by a `<label for="...">bla</label>` tag. This is due to the way `yii\widgets\ActiveForm::checkbox` was implemented. The bootstrap variant of `ActiveForm` will inherit that behavior.

**Comment by nigelterry** [comment]
Your proposed workaround doesn't work for me. I now get both labels.

This:
                        <div class="col-md-4 col-xs-12">
                            <?= $form->field($searchModel, 'status')->label('Hide Contingent Listings')
                                ->checkbox(['uncheck' => '', 'value' => 'ACTIVE']) ?>
                        </div>

Generates this: (status is the model attribute)
<div class="checkbox">
<label class="control-label">
<input type="hidden" name="ListingSearch[status]" value=""><label><input type="checkbox" id="listingsearch-status" name="ListingSearch[status]" value="ACTIVE"> Status</label>
Hide Contingent Listings
</label>
<p class="help-block help-block-error"></p>

</div>

**Comment by mikehaertl** [comment]
@nigelterry Are you sure, you undid the changes you suggested above? You can also try my suggested fix (see linked PR above)

**Comment by nigelterry** [comment]
Yes, I undid my changes. I also fixed the markup in my last comment

**Comment by mikehaertl** [comment]
That's weird. I just tested with this code:

```
<?= $form->field($model, 'rememberMe')->label('bla')->checkbox(['uncheck' => '', 'value' => 'ACTIVE']) ?>
```

The generated markup for me is:

```
<div class="form-group field-loginform-rememberme">
  <div class="checkbox">
    <label class="control-label">
      <input type="hidden" name="LoginForm[rememberMe]" value=""><input type="checkbox" id="loginform-rememberme" name="LoginForm[rememberMe]" value="ACTIVE">
      bla
    </label>
    <p class="help-block help-block-error"></p>
  </div>
</div>
```

So I'm pretty sure this works.

But apart from that, can you also test my PR above to see if it fixes the issue for you? Please make sure, that you really download the raw file from that PR:
https://raw.githubusercontent.com/mikehaertl/yii2-bootstrap/7895-label-option/ActiveField.php

**Comment by nigelterry** [comment]
OK. I just got the latest ActiveField from Git. That works correctly and I only get a single label. Diff shows one change 'fixed issue with wrongly assigned label in bootstrap' where this was added:
```        }
        if (!isset($options['for'])) {
            $options['for'] = Html::getInputId($this->model, $this->attribute);

**Comment by mikehaertl** [comment]
Not sure what you mean. That diff is from a previous commit. My fix does not include that change.

I'm still pretty sure, that you forgot to undo your change in line 210 above. Maybe try again with the clean original file from [here](https://raw.githubusercontent.com/yiisoft/yii2-bootstrap/2.0.3/ActiveField.php) for version 2.0.3. The `label()` method must work.

**Comment by nigelterry** [comment]
I pulled that version and the workaround now work. You are correct, I didn't know what I did. Probably didn't save or upload. My Bad. Now I get this result with the workaround:

```<div class="checkbox">
<label class="control-label">
<input type="hidden" name="ListingSearch[status]" value=""><input type="checkbox" id="listingsearch-status" name="ListingSearch[status]" value="ACTIVE">
Hide Contingent Listings
</label>
<p class="help-block help-block-error"></p>

</div>
```
Sorry for the confusion.

**Comment by mikehaertl** [comment]
Ok, to sum it up:

 * the fix in the PR works for you
 * the workaround with `label()` also works for you

**Comment by nigelterry** [comment]
The workaround is perfect. Fixes the problem with or without the 'fixed issue with wrongly assigned label in bootstrap' patch applied.

The 'fixed issue with wrongly assigned label in bootstrap' does not fix the original problem. It still uses the model attribute and generates:
```
<div class="checkbox">
<label for="listingsearch-status">
<input type="hidden" name="ListingSearch[status]" value=""><input type="checkbox" id="listingsearch-status" name="ListingSearch[status]" value="ACTIVE">
Status
</label>
<p class="help-block help-block-error"></p>

</div>
```

**Comment by mikehaertl** [comment]
@nigelterry Can you give the code you used? Again: are you sure, you've used the correct file? I've tested and it fixed the problem here, so it's unlikely that it doesn't work for you.

**Comment by nigelterry** [comment]
OK. I have ActiveField as the version without my code. It does have the later fix:
```
        }
        if (!isset($options['for'])) {
            $options['for'] = Html::getInputId($this->model, $this->attribute);
```
My code looks like:
```
<div class="col-md-4 col-xs-12">
    <?= $form->field($searchModel, 'status')
        ->checkbox(['label' => 'Hide Contingent Listings', 'uncheck' => '', 'value' => 'ACTIVE']) ?>
</div>
```
And that generates:
```
<div class="col-md-4 col-xs-12">
                            <div class="form-group field-listingsearch-status">
<div class="checkbox">
<label for="listingsearch-status">
<input type="hidden" name="ListingSearch[status]" value=""><input type="checkbox" id="listingsearch-status" name="ListingSearch[status]" value="ACTIVE">
Status
</label>
<p class="help-block help-block-error"></p>

</div>
```

**Comment by mikehaertl** [comment]
> OK. I have ActiveField as the version without my code. It does have the later fix:
> ```
>         }
>        if (!isset($options['for'])) {
>           $options['for'] = Html::getInputId($this->model, $this->attribute);
> ```


I don't understand what you mean by that or where you got that fix from. That's not my fix. The correct diff is here: https://github.com/yiisoft/yii2-bootstrap/pull/18/files

You should really download the correct file from here: https://raw.githubusercontent.com/mikehaertl/yii2-bootstrap/7895-label-option/ActiveField.php

**Comment by nigelterry** [comment]
I apologize again. I missed your earlier posting of your proposed fix. I'm trying to do too many things at once here. The only change I saw in Git was the one from 25 days ago be Cebe, and that made no difference as you would expect.

Your fix at https://raw.githubusercontent.com/mikehaertl/yii2-bootstrap/7895-label-option/ActiveField.php works perfectly to solve the original problem. It gives:

```
<div class="checkbox">
<label for="listingsearch-status">
<input type="hidden" name="ListingSearch[status]" value=""><input type="checkbox" id="listingsearch-status" name="ListingSearch[status]" value="ACTIVE">
Hide Contingent Listings
</label>
<p class="help-block help-block-error"></p>
```

**Comment by pana1990** [comment]
Relation https://github.com/yiisoft/yii2/issues/7794

**Comment by mikehaertl** [comment]
So this here should be closed as duplicate of #7794.
