### ISSUE TITLE
"XML5605: Unrecognized input encoding signature." in IE11 when enabling Yii2 debug module

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#9169]
When Yii2 debug module is enabled:
```
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';
```
IE11 complains in console (F12, "Console" tab) on every site page with an error message:
```
XML5605: Unrecognized input encoding signature.
```
When Yii2 debug module is disabled that error message does not appear.

**Comment by cbhp** [comment]
That error is tolerated since Yii generates additional css for the debug toolbar and inserts it into the body. But <style> tag is not allowed in <body> tag.
Verify: Comment out the line 184 and error XML5605 disappears.
https://github.com/yiisoft/yii2-debug/blob/5c3a3a8c662bcbc84e384af1207354ce0088801d/Module.php#L184

**Comment by samdark** [comment]
Fixed registering script / style. Now styles are in the head. Is it any better now?

**Comment by PowerGamer1** [comment]
> Fixed registering script / style. Now styles are in the head. Is it any better now?

With latest yii2-debug (https://github.com/yiisoft/yii2-debug/archive/master.zip) it is much worse now. Before there was only a single XML5605 error during initial page load, now there are many more and the IE11 console is flooded by these errors when scrolling the page.

Disabling debug module still gets rid of the errors.

**Comment by samdark** [comment]
Found the reason. Fixing...

**Comment by samdark** [comment]
Done https://github.com/yiisoft/yii2-debug/commit/69ab71b950f05c89ab347e9aeeb2726fb4fd4bad
